CNWeb/Areas/Admin/Controllers/CategoryController.cs
using Models.DAO;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CNWeb.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateCategory(CATEGORY model)
        {
            if (ModelState.IsValid)
            {
                model.MetaKeyword = SlugGenerator.SlugGenerator.GenerateSlug(model.CategoryName);
                
                int result = await new CategoryDAO().CreateCateProc(model);
                return RedirectToAction("CreateCategory");
            }
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> EditCategory(CATEGORY model, string id)
        {
            if (ModelState.IsValid)
            {
                model.MetaKeyword = SlugGenerator.SlugGenerator.GenerateSlug(model.CategoryName);
                int result = await new CategoryDAO().EditCateProc(model, id);
                if (result == 0)
                {
                    return Json(new { Success = false, id }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { Success = true, id }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, id }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> CategoryList()
        {
            return PartialView("CategoryList", await new CategoryDAO().LoadDataProc());
        }

        [HttpPost]
        public async Task<JsonResult> DeleteCategory(string id)
        {
            if (await new CategoryDAO().LoadByIDProc(id) == null)
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            if (!(await new CategoryDAO().DeleteCateProc(id)))
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = 1 }, JsonRequestBehavior.AllowGet);
        }
    }
}

CNWeb/Areas/Admin/Controllers/CustomerController.cs
using Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CNWeb.Areas.Admin.Controllers
{
    public class CustomerController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CustomerList()
        {
            return PartialView("CustomerList", await new CustomerDAO().LoadCustomerProc());
        }

        [HttpPost]
        public async Task<JsonResult> DeleteCustomer(int id)
        {
            if (await new CustomerDAO().LoadByIDProc(id) == null)
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            if (!(await new CustomerDAO().DeleteCustomerProc(id)))
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = 1 }, JsonRequestBehavior.AllowGet);
        }
    }
}

CNWeb/Areas/Admin/Controllers/ProductController.cs
using Models.DAO;
using Models.EF;
using CNWeb.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.SqlClient;

namespace CNWeb.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        /// <summary>
        /// Product
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //[HttpPost]
        //public ActionResult DeleteProduct(int id)
        //{
        //    if (new ProductDAO().LoadByID(id) == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    if (!(new ProductDAO().Delete(id)))
        //    {
        //        return HttpNotFound();
        //    }
        //    return RedirectToAction("ProductList");
        //}

        [HttpPost]
        public async Task<JsonResult>  DeleteProduct(string id)
        {
            if ( new ProductDAO().LoadByIDProc(id) == null)
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            if (!(await new ProductDAO().DeleteProductProc<PRODUCT>(id)))
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            var del = new ProductDetailDAO().DeleteProductDetail(id);
            return Json(new { Success = 1 }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> ProductList()
        {
            return View(await new ProductDAO().LoadProductProc());
        }

        public async Task<ActionResult> CreateProduct()
        {
            ViewBag.Cate = await new CategoryDAO().LoadDataProc();
            ViewBag.Size = await new SizeDAO().LoadDataProc();
            return View();
        }
       
        [HttpPost]
        public async Task<JsonResult> CreateProduct(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                string descript = new ProductDAO().checkdes(model.ProductDescription);
                string img_1 = new ProductDAO().checkimg1(model.ShowImage_1);
                string img_2 = new ProductDAO().checkimg2(model.ShowImage_2);
                var db = new CNWebDbContext();
                var id = new SqlParameter("@id", model.ProductID);
                var name = new SqlParameter("@name", model.ProductName);
                var des = new SqlParameter("@description", descript);
                var price = new SqlParameter("@price", model.ProductPrice);
                var promotion = new SqlParameter("@promotionprice", model.PromotionPrice);
                var img1 = new SqlParameter("@img1", img_1);
                var img2 = new SqlParameter("@img2",img_2);
                var stock = new SqlParameter("@stock", model.ProductStock);
                var meta = new SqlParameter("@meta", SlugGenerator.SlugGenerator.GenerateSlug(model.ProductName));
                var status = new SqlParameter("@status", model.ProductStatus);
                var cate = new SqlParameter("@cate", model.CategoryID);

                var result = await db.Database.ExecuteSqlCommandAsync("Create_Product @id, @name,@description,@price,@promotionprice,@img1,@img2,@stock,@meta,@status,@cate", id, name, des, price, promotion, img1, img2, stock, meta, status, cate);

                var res = new ProductDetailDAO().AddProductDetail(model.ProductID, model.Size);

                return Json(new { Success = true, id = 1 }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Size
        /// </summary>
        /// <returns></returns>
        [ActionName("Size")]
        public ActionResult CreateSize()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateSize(SIZE model)
        {
            if (ModelState.IsValid)
            {
                int result = await new SizeDAO().CreateSizeProc(model);
                return RedirectToAction("Size");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> SizeList()
        {
            return PartialView("SizeList", await new SizeDAO().LoadDataProc());
        }

        [HttpPost]
        public async Task<JsonResult> DeleteSize(int id)
        {
            if ( await new SizeDAO().LoadByIDProc(id) == null)
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            if (!( await new SizeDAO().DeleteSizeProc(id)))
            {
                return Json(new { Success = 0 }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = 1 }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> EditSize(SIZE model, int id)
        {
            if (ModelState.IsValid)
            {
                int result = await new SizeDAO().EditSizeProc(model, id);
                if (result == 0)
                {
                    return Json(new { Success = false, id }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { Success = true, id }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, id }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> EditProduct(string id)
        {
            var prod = await new ProductDAO().LoadByIDProc(id);
            ViewBag.ProductID = prod.ProductID;
            ViewBag.Name = prod.ProductName;
            ViewBag.Description = prod.ProductDescription;
            ViewBag.Price = prod.ProductPrice;
            ViewBag.PromotionPrice = prod.PromotionPrice;
            ViewBag.Img1 = prod.ShowImage_1;
            ViewBag.Img2 = prod.ShowImage_2;
            ViewBag.Stock = prod.ProductStock;
            ViewBag.Cate = await new CategoryDAO().LoadDataProc();
            ViewBag.Size = await new SizeDAO().LoadDataProc();
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> EditProduct(ProductModel model, string id)
        {
            if (ModelState.IsValid)
            {
                string descript = new ProductDAO().checkdes(model.ProductDescription);
                string img_1 = new ProductDAO().checkimg1(model.ShowImage_1);
                string img_2 = new ProductDAO().checkimg2(model.ShowImage_2);
            
                var db = new CNWebDbContext();
                var prodID = new SqlParameter("@id", id);
                var name = new SqlParameter("@name", model.ProductName);
                var des = new SqlParameter("@description", descript);
                var price = new SqlParameter("@price", model.ProductPrice);
                var promotion = new SqlParameter("@promotionprice", model.PromotionPrice);
                var img1 = new SqlParameter("@img1", img_1);
                var img2 = new SqlParameter("@img2", img_2);
                var stock = new SqlParameter("@stock", model.ProductStock);
                var meta = new SqlParameter("@meta", SlugGenerator.SlugGenerator.GenerateSlug(model.ProductName));
                var status = new SqlParameter("@status", model.ProductStatus);
                var cate = new SqlParameter("@cate", model.CategoryID);

                var result = await db.Database.ExecuteSqlCommandAsync("Update_Product @id,@name,@description,@price,@promotionprice,@img1,@img2,@stock,@meta,@status,@cate", prodID, name, des, price, promotion, img1, img2, stock, meta, status, cate);
                var del = new ProductDetailDAO().DeleteProductDetail(id);
                var res = new ProductDetailDAO().AddProductDetail(id, model.Size);

                return Json(new { Success = true, id = 1 }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
        }
    }
}

CNWeb/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>@ViewBag.Title</title>
    <link href="~/Areas/Admin/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Areas/Admin/assets/css/icons.css" rel="stylesheet">
    <link href="~/Areas/Admin/assets/css/menu.css" rel="stylesheet" type="text/css">
    <link href="~/Areas/Admin/assets/css/style.css" rel="stylesheet">
</head>

<body class="sticky-header">
    <section>
        @Html.Partial("_LeftBar")
        <div class="body-content">
            <div class="header-section">
                <div class="logo">
                </div>
                <a class="toggle-btn"><i class="ti ti-menu"></i></a>
                <div id="navbar-collapse-1" class="navbar-collapse collapse mega-menu">
                    <ul class="nav navbar-nav">
                        <li>
                            <form class="search-content" action="index.html" method="post">
                                <input type="text" class="form-control mt-3" name="keyword" placeholder="Search...">
                                <span class="search-button"><i class="ti ti-search"></i></span>
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="notification-wrap">
                    <div class="right-notification">
                        <ul class="notification-menu">
                            <li>
                                <a href="javascript:;" data-toggle="dropdown">
                                    <i class="mdi mdi-account"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right profile-menu">
                                    <a class="dropdown-item" href="#"><i class="mdi mdi-account-circle m-r-5 text-muted"></i> Profile</a>
                                    <a class="dropdown-item" href="@Url.Action("Logout", "Admin")">
                                        <i class="mdi mdi-logout m-r-5 text-muted"></i>
                                        Logout
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <hr />
            @RenderBody()
        </div>
    </section>
    <script src="~/Areas/Admin/assets/js/jquery-3.2.1.min.js"></script>

    <script src="~/Areas/Admin/assets/js/popper.min.js"></script>
    <script src="~/Areas/Admin/assets/js/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/assets/js/jquery.slimscroll.min.js"></script>
    <script src="~/Areas/Admin/assets/js/slidebars.min.js"></script>

    <script src="~/Areas/Admin/assets/js/jquery.app.js"></script>


    @RenderSection("scripts", required: false)
</body>
</html>

CNWeb/Areas/Admin/Views/Shared/_LeftBar.cshtml
<div class="sidebar-left position-fixed">
    <div class="sidebar-left-info">
        <div class="user-box">
            <div class="text-center text-white mt-2">
                <h6>Travis Watson</h6>
                <p class="text-muted m-0">Admin</p>
            </div>
        </div>
        <ul class="side-navigation">
            <li>
                <h3 class="navigation-title">Navigation</h3>
            </li>
            <li class="active">
                <a href="@Url.Action("Index", "Home")" title="Home"><i class="mdi mdi-gauge"></i> <span>Home</span></a>
            </li>
            <li>
                <h3 class="navigation-title">Components</h3>
            </li>
            <li class="menu-list">
                <a href=""><i class="mdi mdi-cart"></i> <span>Product</span></a>
                <ul class="child-list">
                    <li>
                        <a href="@Url.Action("CreateProduct", "Product")" title="Add new">
                            <i class="mdi mdi-file-document-box"></i>
                            <span> Create Product</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("ProductList", "Product")" title="List">
                            <i class="mdi mdi-format-list-bulleted"></i>
                            <span> Product List</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Size", "Product")" title="Size">
                            <i class="mdi mdi-format-align-center"></i>
                            <span> Size Option</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="@Url.Action("CreateCategory", "Category")" title="Add new">
                            <i class="mdi mdi-tag"></i>
                            <span> Category</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="menu-list">
                <a href="">
                    <i class="mdi mdi-shopping"></i>
                    <span>Order</span>
                </a>
                <ul class="child-list">
                    <li>
                        <a href="@Url.Action("Order", "Order")" title="Add new">
                            <i class="mdi mdi-format-list-bulleted"></i>
                            <span> Order List</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="@Url.Action("Index", "Customer")" title="Customer">
                    <i class="mdi mdi-account">
                    </i> <span>Customer</span>
                </a>
            </li>
        </ul>

    </div>
</div>